version: '3'

services:
  nginx:
    build: ./nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/nginx/vhost.d:/etc/nginx/vhost.d
    links:
      - maria_db
      - api
      - roof-calc
      - phpmyadmin
  api:
    build: ./api
    ports:
      - 3004:3333
    volumes:
      - ./api/src:/src
    environment:
      VIRTUAL_HOST: api.tak.local

  roof-calc:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    volumes:
      - ./frontend/src:/app
    ports:
      #- 5010:5000
      - 3000:3000
    environment:
      VIRTUAL_HOST: tak.local

  maria_db:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8003:80
    environment:
      VIRTUAL_HOST: db.tak.local
      PMA_HOST: maria_db


